### ISSUE TITLE
Avatar images are very blurry and unrecognizable

### ISSUE THREAD

**Issue by kiliman** [leereilly/github-high-scores#2]
I understand that you're trying to give the avatar's an 8-bit look, but they are shrunken and resized to the point where they are just blurry and unrecognizable as the original image.

I played around with ImageMagick and came up with a way to make an image look "8-bit" yet still look like the original.

Here's a page I mocked up with some sample images: http://www.systemex.net/files/github-high-scores/8-bit-avatar.html

I used ImageMagick to convert the image. First resize to 24x24 and recolor using "websafe" colors using halftone dithering, then finally scale up to 48x48.

My understanding is that there is a Ruby library to interface with ImageMagick, so hopefully it would be doable. [RMagic](http://rmagick.rubyforge.org)

```
convert filename.jpg -resize 24x24 -remap netscape: -ordered-dither h4x4a -scale 200% filename_8bit.gif 
```

**Comment by williamd1k0** [comment]
What about using `image-rendering` in css?

I tried using `pixelated` on Google Chrome.

![image](https://cloud.githubusercontent.com/assets/10428035/19017879/fbab41a2-8822-11e6-95dd-08db809e9946.png)
